### ISSUE TITLE
弹窗允许授予权限后

### ISSUE THREAD

**Issue by bayshier** [lilongweidev/Android12Bluetooth#2]
Process: com.llw.bluetooth, PID: 17057
                                                                                                    java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@f8f022c4: AdapterService getRemoteName
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2392)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2334)
                                                                                                    	at android.bluetooth.IBluetooth$Stub$Proxy.getRemoteName(IBluetooth.java:3395)
                                                                                                    	at android.bluetooth.BluetoothDevice.getName(BluetoothDevice.java:1273)
                                                                                                    	at com.llw.bluetooth.MainActivity.addDeviceList(MainActivity.kt:116)
                                                                                                    	at com.llw.bluetooth.MainActivity.access$addDeviceList(MainActivity.kt:23)
                                                                                                    	at com.llw.bluetooth.MainActivity$scanCallback$1.onScanResult(MainActivity.kt:91)
                                                                                                    	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:531)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)

**Comment by lilongweidev** [comment]
Li
***@***.***



&nbsp;
在使用蓝牙之前，你需要先请求BLUETOOTH_CONNECT ，允许之后再通过适配器打开蓝牙开关，然后扫描之前请求BLUETOOTH_SCAN权限


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lilongweidev/Android12Bluetooth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月11日(星期一) 中午11:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lilongweidev/Android12Bluetooth] 弹窗允许授予权限后 (Issue #2)





 
Process: com.llw.bluetooth, PID: 17057
 java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for ***@***.***: AdapterService getRemoteName
 at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
 at android.os.Parcel.createException(Parcel.java:2409)
 at android.os.Parcel.readException(Parcel.java:2392)
 at android.os.Parcel.readException(Parcel.java:2334)
 at android.bluetooth.IBluetooth$Stub$Proxy.getRemoteName(IBluetooth.java:3395)
 at android.bluetooth.BluetoothDevice.getName(BluetoothDevice.java:1273)
 at com.llw.bluetooth.MainActivity.addDeviceList(MainActivity.kt:116)
 at com.llw.bluetooth.MainActivity.access$addDeviceList(MainActivity.kt:23)
 at com.llw.bluetooth.MainActivity$scanCallback$1.onScanResult(MainActivity.kt:91)
 at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:531)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
